# Generated by Django 4.1.4 on 2022-12-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("help_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="branch_code",
            field=models.CharField(
                error_messages={"unique": "Branch code already assign to other Branch"},
                max_length=3,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="branch",
            name="branch_name",
            field=models.CharField(
                error_messages={"unique": "Branch already Present"},
                max_length=32,
                unique=True,
            ),
        ),
    ]
